# Generated by Django 3.1.5 on 2021-01-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Product 6 digits code', max_length=20)),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('specification', models.CharField(help_text='Product specifications', max_length=300)),
                ('size', models.CharField(help_text='Product size', max_length=100)),
                ('singular_unit', models.CharField(choices=[('pieces', 'PCS'), ('meter', 'M')], default='pieces', help_text='Product singular unit', max_length=10)),
                ('plural_unit', models.CharField(choices=[('box', 'BOX'), ('coil', 'COIL'), ('bar', 'BAR')], default='box', help_text='Product plural unit', max_length=10)),
                ('package_quantity', models.IntegerField(default=0, help_text='Product package quantity', max_length=10)),
                ('image', models.ImageField(default='product.jpg', help_text='Product image', upload_to='products_images')),
            ],
        ),
    ]
