# Generated by Django 3.1.5 on 2021-01-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_products_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, help_text='Product size', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='specification',
            field=models.CharField(blank=True, help_text='Product specifications', max_length=300),
        ),
    ]
