# Generated by Django 3.1.5 on 2021-01-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210119_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Pipe & Fittings', 'PIPE_FITTING'), ('Valves', 'VALVE'), ('Manifolds', 'MANIFOLD'), ('Underfloor Heating', 'UFH'), ('Tools', 'TOOL')], default='PIPE_FITTING', max_length=200),
        ),
    ]
