# Generated by Django 3.1.5 on 2021-01-21 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210120_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('code', 'name', 'specification', 'size')},
        ),
    ]
