# Generated by Django 3.1.5 on 2021-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210120_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('PIPE_FITTING', 'لوله و اتصالات'), ('VALVE', 'شیرآلات'), ('MANIFOLD', 'کلتور'), ('UFH', 'گرمایش از کف'), ('TOOL', 'ابزار')], default='PIPE_FITTING', max_length=200, verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(help_text='Product 6 digits code', max_length=20, verbose_name='کد محصول'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='product.jpg', help_text='Product image', upload_to='products_images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(help_text='Product name', max_length=200, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='products',
            name='package_quantity',
            field=models.IntegerField(default=1, help_text='Product package quantity', verbose_name='تعداد در بسته'),
        ),
        migrations.AlterField(
            model_name='products',
            name='plural_unit',
            field=models.CharField(choices=[('BOX', 'کارتن'), ('COIL', 'رول'), ('BAR', 'شاخه')], default='BOX', help_text='Product plural unit', max_length=10, verbose_name='واحد بسته'),
        ),
        migrations.AlterField(
            model_name='products',
            name='singular_unit',
            field=models.CharField(choices=[('PCS', 'عدد'), ('M', 'متر')], default='PCS', help_text='Product singular unit', max_length=10, verbose_name='واحد'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, help_text='Product size', max_length=100, verbose_name='سایز'),
        ),
        migrations.AlterField(
            model_name='products',
            name='specification',
            field=models.CharField(blank=True, help_text='Product specifications', max_length=300, verbose_name='مشخصات'),
        ),
    ]
