# Generated by Django 3.1.5 on 2021-01-23 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210122_1920'),
        ('products', '0008_auto_20210121_0616'),
    ]

    operations = [
    ]
