# Generated by Django 3.1.5 on 2021-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('user_first_name', models.CharField(max_length=200)),
                ('user_last_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('user_cellphone', models.CharField(max_length=200)),
                ('user_password', models.CharField(max_length=200)),
                ('user_profile_image', models.FileField(upload_to='')),
                ('user_create_date', models.DateTimeField()),
                ('user_last_login_date', models.DateTimeField()),
            ],
        ),
    ]
