# Generated by Django 3.1.5 on 2021-01-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210108_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_last_login_date',
            field=models.DateTimeField(blank='true'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.FileField(blank='true', upload_to=''),
        ),
    ]
