# Generated by Django 3.1.5 on 2021-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210108_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_create_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_last_login_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
