# Generated by Django 3.1.5 on 2021-01-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210108_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_profile_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbWMHsOFSpe0SQ9au-xUAPizVVualR_yqqMg&usqp=CAU', max_length=500),
        ),
    ]
