# Generated by Django 3.1.5 on 2021-01-15 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210114_0801'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_cellphone',
            new_name='cellphone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_create_date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_last_login_date',
            new_name='last_login_date',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_profile_image',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='username',
        ),
    ]
