# Generated by Django 3.1.5 on 2021-01-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210116_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='cellphone',
            field=models.CharField(max_length=200, verbose_name='تلفن همراه'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='firstname',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین ورود'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(default='profile.jpg', upload_to='profile_images', verbose_name='عکس'),
        ),
    ]
