# Generated by Django 3.1.5 on 2021-01-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210123_1922'),
        ('user', '0011_auto_20210123_0443'),
    ]

    operations = [
    ]
